### ISSUE TITLE
Makes the game crash to the desktop

### ISSUE THREAD

**Issue by ppujols96** [kosch104/RadioMediaControl#1]
If tis mod is enabled, as soon as the game reach the main menu, the game crashes to the desktop or sometime does not even go beyond the splash screen.

[Logs.zip](https://github.com/kosch104/RadioMediaControl/files/14906147/Logs.zip)

**Comment by Mimonsi** [comment]
There are no issue when the mod is disabled and everything else is enabled normally? Is Skyve showing any errors at all? 

There are no errors in the log files, and the mod seems to be working fine.

**Comment by ppujols96** [comment]
A: I installed the mod through Skyve and opened the game through there and did not work.
B: I disabled the mod in Skyve and try again and the game opened normally.
C: Repeated the same but with PDXM directly from the game. Since a mod change was made I had to restart the game but it crashed again. 

As soon as the mod is enabled the game does not reach the main manu and crashes.

I did not see anything in the logs either, is because the mod does not even execute/run?

**Comment by Mimonsi** [comment]
The mod seems to run, but it doesn't throw any errors. Could you try to delete all your logs and create a playset that ONLY contains extended radio and Radio Media Control? Then please attach the log files again, including the Player.log in the parent direcotry.

**Comment by Mimonsi** [comment]
Issue will be closed until further information is supplied.
